name: master-push-action
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
      with:
        fetch-depth: 2
    - run: sudo apt-get install clang-14 clang-tools-14 clang-14-doc libclang-common-14-dev libclang-14-dev libclang1-14 clang-format-14 python3-clang-14 clangd-14 clang-tidy-14
    - run: clang --version
    - run: git config --global clangFormat.style file
    - run: git config --global --path clangFormat.stylePath .clang-format
    - run: |
          DIFFERECE="$(git clang-format --diff HEAD~ HEAD)"
          echo "${DIFFERECE}"
          if [[ $DIFFERECE != "no modified files to format" && $DIFFERECE != "clang-format did not modify any files" ]]; then
            exit 1
          fi
