name: master-push-action
on:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
      with:
        fetch-depth: 2
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
    - run: npm install clang-format
    - run: git config --global clangFormat.style file
    - run: git config --global --path clangFormat.stylePath .clang-format
    - run: |
          DIFFERECE = "$(git clang-format --diff HEAD~ HEAD)"
          echo "${DIFFERECE}"
