name: master-push-action
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
      with:
        fetch-depth: 2
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
    - run: npm install clang
    - run: git config --global clangFormat.style file
    - run: git config --global --path clangFormat.stylePath .clang-format
    - run: |
          DIFFERECE="$(git clang-format-15 --diff HEAD~ HEAD)"
          echo "${DIFFERECE}"
          if [[ $DIFFERECE != "no modified files to format" && $DIFFERECE != "clang-format did not modify any files" ]]; then
            exit 1
          fi
