name: master-push-action
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
      with:
        fetch-depth: 2
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1.6.0
      with:
        version: "14.0"
    - name: Configure git clang-format
      run: |
        git config --global clangFormat.style file
        git config --global --path clangFormat.stylePath .clang-format
    - name: Check formating of changes
      run: |
          DIFFERECE="$(git clang-format --diff HEAD~ HEAD)"
          echo "${DIFFERECE}"
          if [[ $DIFFERECE != "no modified files to format" && $DIFFERECE != "clang-format did not modify any files" ]]; then
            exit 1
          fi
    - name: Write AST to ast.txt
      run: clang++ -Xclang -ast-dump -fsyntax-only Main.cpp > ast.txt || true
    - name: Print code complexity 
      run: |
          touch Complexity.txt
          wc -l ast.txt > Complexity.txt
          cat Complexity.txt
    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.1
      with:
        add: Complexity.txt
        message: 'complexity commit'
