name: master-push-action
on:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
      with:
        fetch-depth: 2
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
    - run: npm install clang-format
    - run: git config --global clangFormat.style file
    - run: git config --global --path clangFormat.stylePath .clang-format
    - run: |
        difference = git clang-format --diff HEAD~ HEAD
        if: ${difference}!='no modified files to format' && ${difference}!='clang-format did not modify any files'; then
          exit 1
        fi
