name: master-push-action
on:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
      with:
        fetch-depth: 2
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
    - run: npm install clang-format
    - run: git config --global clangFormat.style file
    - run: git config --global --path clangFormat.stylePath .clang-format
    - env:
        DIFFERENCE: git clang-format --diff HEAD~ HEAD
        FIRST_CONDITION: $DIFFERENCE != 'no modified files to format'
        SECOND_CONDITION: $DIFFERENCE != 'clang-format did not modify any files'
      if: $FIRST_CONDITION && $SECOND_CONDITION
      run: |
        echo $DIFFERENCE
        echo $FIRST_CONDITION
        echo $SECOND_CONDITION
        exit 1