name: master-push-action
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
      with:
        fetch-depth: 2
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1.6.0
      with:
        version: "14.0"
    - name: Configure git clang-format
      run: |
        git config --global clangFormat.style file
        git config --global --path clangFormat.stylePath .clang-format
    - name: Check formating of changes
      run: |
          DIFFERENCE="$(git clang-format --diff HEAD~ HEAD)"
          echo "${DIFFERENCE}"
          if [[ $DIFFERENCE != "no modified files to format" && $DIFFERECE != "clang-format did not modify any files" ]]; then
            exit 1
          fi
    - name: Write AST to ast.txt
      run: clang++ -Xclang -ast-dump -fsyntax-only Main.cpp > ast.txt || true
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.1
      with:
        name: Complexity
    - run: wc -l ast.txt | awk '{print "Current complexity:",$1;}' > Complexity.txt
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: Complexity
        path: Complexity.txt
